version: "2"

linters:
  default: none
  enable:
    - depguard
    - misspell
    - revive
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: "github.com/pkg/errors"
              desc: use stdlib errors and fmt.Errorf with %w instead
    revive:
      rules:
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
        - name: indent-error-flow
          disabled: true
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log

formatters:
  enable:
    - goimports
    - gofmt
  settings:
    goimports:
      local-prefixes:
        - github.com/grafana/e2e

run:
  timeout: 5m
  build-tags:
    - netgo
    - requires_docker
